---
abstract: 'Use Memcached for cache storage'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CHI-Driver-Memcached
no_index:
  directory:
    - lib/CHI/Driver/Memcached/t
    - lib/CHI/Driver/Memcached/Test
requires:
  CHI: 0.33
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CHI-Driver-Memcached
  repository: git://github.com/jonswar/perl-chi-driver-memcached.git
version: 0.14
